[package]
name = "example-plugin"
version = "0.1.0"
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
example-bindings = { path = "../bindings/rust-plugin" }
chrono = "0.4.19"
