[package]
name = "fp-bindgen-support"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
once_cell = "1"
rmp-serde = "=1.0.0-beta.1"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
